[project]
name = "my_uv_project"
version = "0.1.0"
description = "Template Python project using uv"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10"

lockfile = "requirements.lock.txt"
